### ISSUE TITLE
A QoL Regression

### ISSUE THREAD

**Issue by leion247** [ScintillaOrg/lexilla#95] opened 2022-07-17 22:26 UTC
There has been a regression. This line before the 0 used to appear as blue (Shown below), which is the correct thing to do in my yml files. Been that way for years and is very helpful. However, version 5.1.0 caused this to no longer be the case, and has negatively impacted my work. I’m currently staying in Notepad++ 8.1.5, when this wasn't changed, until this issue is resolved. Do you believe you could add an option or something that could fix this?
![1657482584154-untitled](https://user-images.githubusercontent.com/37279499/179426926-4e1155cb-4ae2-461f-9fa2-eba04fdc16e2.png)
![Untitled](https://user-images.githubusercontent.com/37279499/179427023-0e383950-5eae-4645-b525-9669741dc264.png)

**Comment by nyamatongwe** [comment] 2022-07-18 00:16
This was caused by #15,  is deliberate, and appears to be following the YAML specification https://yaml.org/spec/1.2.2/#21-collections.

**Comment by leion247** [comment] 2022-07-18 02:08
Hmmm, it would appear you're correct. How inconvenient. Should I assume there is nothing that can be done to make it visually do what it used to without actually affecting the correction put in place through some sort of option? If not, I'll unfortunately need to stay in 8.1.5 of Notepad++. The negative impact on my work really is too great to not have this effectively accidental QoL feature.

**Comment by nyamatongwe** [comment] 2022-07-18 22:43
For an option, there would have to be a more widespread need for this. Its not even clear what the given text is supposed to mean in YAML.

I am closing this issue for now as the examples do not match the YAML specification.

**Closed by nyamatongwe** 2022-07-18 22:43 UTC
Labels: yaml
