### ISSUE TITLE
[JS] exclude ${} from backtick highlighting

### ISSUE THREAD

**Issue by TomRobert** [ScintillaOrg/lexilla#114] opened 2022-11-02 16:42 UTC
Is it possible to not highlight the ${} and text inside of it, in a backtick string in Javascript? To improve readability.

Example of Notepad++ (and the double quote string for comparison):
![image](https://user-images.githubusercontent.com/10408976/199548645-b8c197c3-6afd-4e0c-8ce6-cc82678fcb2f.png)

Example of how it could look like:
![image](https://user-images.githubusercontent.com/10408976/199545477-2d8934f8-a94f-408d-9058-ffe6ce757f11.png)

**Comment by nyamatongwe** [comment] 2022-11-02 22:13
This appears to be a duplicate of #94.

**Closed** 2024-03-12 01:56 UTC
Labels: duplicate, cpp, javascript
