### ISSUE TITLE
Secure overloads inconsistent for win32

### ISSUE THREAD

**Issue by chcg** [ScintillaOrg/lexilla#133] opened 2023-02-15 03:41 UTC
Win32 defines differ between

https://github.com/ScintillaOrg/lexilla/blob/master/src/Lexilla.vcxproj#L75

and

https://github.com/ScintillaOrg/lexilla/blob/master/src/lexilla.mak#L38

regarding `_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES`.

What about adding

`_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT `

https://learn.microsoft.com/en-us/cpp/c-runtime-library/secure-template-overloads?redirectedfrom=MSDN&view=msvc-170

and maybe also enabling

https://learn.microsoft.com/en-us/cpp/build/reference/sdl-enable-additional-security-checks?view=msvc-170

**Comment by nyamatongwe** [comment] 2023-02-15 05:51
The original bug that led to this was [Scintilla 1701](https://sourceforge.net/p/scintilla/bugs/1701/).

As you point out, there is an inconsistency between the project and make files. Even worse, this setting is not available on Unix so there could be different behaviour on Unix. For consistency, `_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES` should not be defined in the make files. Lexer authors may choose to replace `strcpy` with `StringCopy` where appropriate.

**Comment by chcg** [comment] 2023-02-16 04:49
@nyamatongwe My intention was the other way around. 

`_CRT_SECURE_NO_DEPRECATE `is used to disable the warnings to use more secure versions of e.g. 
`strcpy`, `strncpy`, ... which are `strcpy_s`, `strncpy_s`, ... (https://en.cppreference.com/w/c/string/byte/strcpy)

See description in msdn https://msdn.microsoft.com/de-de/library/ms175759.aspx:
From docu:

> The template overloads only work for static arrays. Dynamically allocated buffers require other source code changes.


 
 So `_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES `gives you this change for free in case of e.g. `strcpy`,... and
`_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT  `for `strncpy`,...

So I think it is a good idea to use them already now in nmake and VS config.

**Comment by nyamatongwe** [comment] 2023-02-17 00:00
> My intention was the other way around

I understood that but inconsistencies can be resolved in different directions.

> So I think it is a good idea to use them already now in nmake and VS config.

You haven't addressed the inconsistency with Unix. `strcpy_s` is not portable and hiding it behind `_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES` leads to invisibly divergent behaviour between platforms and runtime libraries.

**Comment by chcg** [comment] 2023-02-18 14:16
Ok. I could understand your point to avoid divergent behaviour between platforms.

The secure versions are part of C11, e.g.:
    C11 standard (ISO/IEC 9899:2011): 
        K.3.7.1.3 The strcpy_s function (p: 615-616) 

, but require changes to all occurrences.

**Comment by nyamatongwe** [comment] 2023-02-18 21:54
From Annex K (Bounds-checking interfaces), section K.2 of the C11 standard:
~~~
This annex specifies a series of optional extensions
~~~
The key here is *optional*. There is a further footnote:
~~~
Implementations that do not define __STDC_LIB_EXT1__ are not required to conform to these
specifications.
~~~
The bounds-checking interface was defined by Microsoft, implemented in their runtime library, and contributed to the C standard but was not implemented by other vendors. Therefore it is not portable and cannot be used in Lexilla.

Scintilla and Lexilla are different: Scintilla is a more unified project but Lexilla can be seen as 118 mini-projects with different authors and users. Each language being lexed comes with its own culture, techniques, and conventions and this may influence the lexer code. The ASN.1 lexer uses `goto` and the Fortran lexer uses fixed-length arrays. Authors often have little knowledge of C++ or better C++ features so fall back to C techniques. This is not a bug and its not something to fix: newer techniques should not be introduced that make it more difficult for the original author(s) to continue contributing. They are the experts on the language and much more likely to notice bugs.

For Scintilla [a recent change](https://sourceforge.net/p/scintilla/code/ci/30ef19cd8f43c7fc6e991a74f0286ae00a4ffe3e/) removed the last `strcpy` from Win32 builds (although the behaviour is still exactly the same, copying into a buffer with unknown size) which will allow omitting `_CRT_SECURE_NO_DEPRECATE` from compilation.

**Closed** 2023-03-08 03:04 UTC
Labels: building, committed
