### ISSUE TITLE
Incorrect mapping for BEGIN and appropriate END keyword

### ISSUE THREAD

**Issue by gal20040** [ScintillaOrg/lexilla#85] opened 2022-05-23 21:00 UTC
### Description of the Issue
There is incorrect mapping for BEGIN and appropriate END keyword.

### Steps to Reproduce the Issue
1.Check the following sql code
```
if (1=1)
begin
	select getdate() --1

	if (2=2)
	begin
		select getdate() --2
		
		if (3=3)
		begin
			select getdate() --3
		end
		
		select getdate() --4
	end

	select getdate() --5
end
```
![image](https://user-images.githubusercontent.com/11201733/169882231-50f5743e-41e9-485b-bfbd-1d9867f5835b.png)
2. Try to collapse outer BEGIN-END block by clicking '-' near BEGIN.

### Expected Behavior
All code inside outer BEGIN-END block should be hide:
![image](https://user-images.githubusercontent.com/11201733/169882365-66405f55-a2fc-43b6-8a1c-ba0321408aea.png)
![image](https://user-images.githubusercontent.com/11201733/169882516-f15112ba-e857-4858-a656-d384bde8639e.png)

### Actual Behavior
There is incorrect hiding of code between outer BEGIN and inner END:
![image](https://user-images.githubusercontent.com/11201733/169882569-72f75850-32ab-42ff-818a-d61b5c8ddab0.png)
![image](https://user-images.githubusercontent.com/11201733/169882591-2faaf307-bf74-4b5c-a1de-adb82435b6ec.png)

![image](https://user-images.githubusercontent.com/11201733/169905435-352ee7d3-bbcb-4890-95e1-a14ecca1d6b9.png)

**Comment by gal20040** [comment] 2022-05-23 21:03
Just to compare with actual correct behaviour in SSMS:
![image](https://user-images.githubusercontent.com/11201733/169882983-945d83ce-3fce-4fc3-b80b-ac6b1e04ea82.png)
![image](https://user-images.githubusercontent.com/11201733/169883029-1ecf64ed-d13e-4f01-8c89-ec9dd60520de.png)

**Comment by nyamatongwe** [comment] 2022-05-23 23:28
Equivalent case:
~~~sql
select getdate()
begin
begin
end
end
~~~

The problem is that the `select` statement isn't seen as terminated so `sqlStatesCurrentLine` is `MASK_INTO_SELECT_STATEMENT_OR_ASSIGNEMENT` (0x200) for the rest of the file causing a double decrement at each `end`.

Adding a `;` to the select `select getdate();` gets it treated as terminated and the folds work.

**Comment by nyamatongwe** [comment] 2022-05-24 22:36
The `sql` lexer is most targeted at Oracle's SQL variant which requires semi-colons. Not handling invalid code isn't really a bug.
https://docs.oracle.com/cd/B14117_01/server.101/b10759/statements_10002.htm#SQLRF01702

There are other SQL variant lexers: `mysql` for MySQL and `mssql` for Microsoft SQL Server.

Here's the `mssql` lexer:
![mssql_select_fold](https://user-images.githubusercontent.com/225818/170143004-9d4d84dd-2d62-467a-97f5-561f76f8dbb9.png)

**Comment by nyamatongwe** [comment] 2022-05-25 22:15
Closing. `;` should be added for `sql` and `mssql` can be used when appropriate.

**Closed by nyamatongwe** 2022-05-25 22:15 UTC
Labels: sql
