### ISSUE TITLE
Standalone header file for version info

### ISSUE THREAD

**Issue by sXNA** [ScintillaOrg/lexilla#142] opened 2023-02-22 15:17 UTC
Hi thanks for awesome project.
I want to ask it is possible to move `#define VERSION_LEXILLA "5.2.2"` from [LexillaVersion.rc](https://github.com/ScintillaOrg/lexilla/blob/master/src/LexillaVersion.rc) into standalone "LexillaVersion.h", same for scintilla.

Sorry if this question does not belong here.

**Comment by nyamatongwe** [comment] 2023-02-22 21:30
The Lexilla version you are using depends on the DLL you are loading, not the headers you compiled with. On Win32 you should call the [winver functions](https://learn.microsoft.com/en-us/windows/win32/api/winver/) starting from `GetFileVersionInfo`.

**Comment by sXNA** [comment] 2023-02-23 17:34
What if project use static library or compile directly with lexilla and scintilla.

**Comment by nyamatongwe** [comment] 2023-02-23 20:38
Statically compiled applications use a single version of Lexilla that is fixed at build time. Why do they need to check the version?

**Comment by sXNA** [comment] 2023-02-24 15:43
For developers convenience, users are asking which version of lexilla and scintilla are used. Also plugin developer could use this information to enable some feature.

Current workaround is using script to get value from [version.txt](https://github.com/ScintillaOrg/lexilla/blob/master/version.txt) or manually type value to project header.

**Comment by nyamatongwe** [comment] 2023-02-24 20:23
> Current workaround is using script to get value from [version.txt](https://github.com/ScintillaOrg/lexilla/blob/master/version.txt).

The build scripts for Lexilla, Scintilla, and SciTE read `version.txt`. What is the problem with that?

**Comment by nyamatongwe** [comment] 2023-03-04 00:11
This proposal seems inadequately justified for now so will be closed as rejected. It can be reopened if there are new arguments for this.

There are different meanings for version numbers:
* Executable version increased when release is announced and delivered. Possibly just fixing bugs.
* Behavioural version increased when new features are added or removed.
* Interface version increased when a new value is added to `LexicalStyles.iface`.
* Possibly more.

Version number use may be performed at package download time, compile time, installation time, or run time with different methods of discovering the version number.

The different meanings for versions could lead to different responses by applications and users. Continued discussion of this issue should clarify which meanings of version are wanted along with how it will be used.

**Comment by rdipardo** [comment] 2023-03-05 12:43
> Continued discussion of this issue should clarify which meanings of version are wanted along with how it will be used.

I would focus on the OP's [earlier point] that application developers currently have no convenient, portable method of extracting library version information at compile time.

The problem isn't obvious if SciTE's help menu is the only point of comparison. The version numbers of SciTE's components are written into the source by tailor-made Python scripts. Every other project still needs to devise and maintain equally non-portable build scripts to achieve the same result.

There is no scriptable solution universal enough for the variety of build systems used by Scintilla and Lexilla's many consumers. The avoidance of scripting altogether is the primary benefit of the OP's original suggestion that a source header should readily expose the current version to the compiler, and thereby to the users of any application programmed to display it, who could then create more useful bug reports with the additional information.

Since the issue pertains to building, potential APIs for runtime version checking can be set aside as out of scope. Version checking is more relevant to plugin modules that may be too bit rotten to safely interface with the host application. No distributed application would ever be incompatible with its own (static) components.

[earlier point]: https://github.com/ScintillaOrg/lexilla/issues/142#issuecomment-1442171592

**Comment by nyamatongwe** [comment] 2023-03-08 06:18
> users are asking which version of lexilla and scintilla

Applications often do not use particular versions of Lexilla and Scintilla but instead use their own modified or augmented versions. For example, Notepad++ merges the Boost regex library into Scintilla as well as adding lexers for `objc`, `searchResult`, and `user`. Some issues reported to Lexilla and Scintilla are due to these modifications or with settings chosen by applications.

> application developers currently have no convenient, portable method of extracting library version information at compile time

The version number can be read at compile time with something like `#include "../../lexilla/version.txt"` - may need more or fewer `../`.

**Comment by nyamatongwe** [comment] 2023-03-13 21:38
Won't implement without a better justification. Closing.

**Closed by nyamatongwe** 2023-03-13 21:38 UTC
